name: Data update
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 0 * * *'

permissions:
  contents: write

jobs:
  # This workflow contains a single job called "build"
  data-update-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -q findspark pyspark
          pip install -q numpy
          pip install -q pandas
          pip install -q pysqlite3
          pip install -q matplotlib
          pip install -q seaborn
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Runs a single command using the runners shell
      - name: Install spark
        run: |
          chmod +x install-spark.sh
          ./install-spark.sh
          ls -lrt
      
      - name: Import db
        run: |
          chmod +x db-import.sh
          ./db-import.sh
          ls -lrt
          
      - name: Read step
        run: |
          export LOCAL_HOME=$(pwd)
          python read.py
          
      - name: Prepare step
        run: |
          export LOCAL_HOME=$(pwd)
          python prepare.py
          
      - name: Process step
        run: |
          export LOCAL_HOME=$(pwd)
          rm -rf export.png
          python process.py
          
      - name: Export step
        run: |
          export LOCAL_HOME=$(pwd)
          python export.py
          
      - name: Push result
        run: |
         git config --global user.email "tkhadir.dev@gmail.com"
         git config --global user.name "tkhadir"
         git add export.png
         git commit -m "feat: add results"
         git push origin
